### ISSUE TITLE
#TODO-레이아웃 구성 1

### ISSUE THREAD

**Issue by GHeeJeon** [my-ggott-games/reborn-reborns#3]
어떤 부분을 바꿀 건데?
어떤 걸 지울 건데?

**Comment by GHeeJeon** [comment]
### 첫 화면
- [ ] 번역 토글 지우기(없애고 풀한글화)
- [ ] 팔레트마냥 늘어놓은 아이콘, 버튼 지우기
- [ ] Reborn reborns! css 적용해서 폰트 색 가히리스럽게 만들기

**Comment by GHeeJeon** [comment]
### 메인 페이지
- [ ] 좌측 상단 로고 변경
- [ ] 우측 상단 프로필 이미지(로 추정되는 것) 변경
- [ ] 상단 검색창, 뭔가 써먹을 수 있을 것 같은데... 당장은 필요없음.
추가 기능은 나중에 고려해보자.
- [ ] 종모양 아이콘은 작동하지 않는다. 당장은 쓸 필요 없으니 삭제
- [ ] components 를 잘~ 갖다써보자!(남겨두자)
- [ ] 그 아래 탭들은 수정 및 삭제-홈이랑 컴포넌트처럼 하위 링크로 연결되게끔

**Comment by GHeeJeon** [comment]
> * 파비콘 변경
<img width="81" alt="스크린샷 2023-04-25 오전 3 21 19" src="https://user-images.githubusercontent.com/47032054/234082881-8d19aac3-159b-4bfd-b527-7dffa65e1577.png">
<img width="300" alt="스크린샷 2023-04-25 오전 3 21 19" src="https://user-images.githubusercontent.com/47032054/234082881-8d19aac3-159b-4bfd-b527-7dffa65e1577.png">
음......

**Comment by GHeeJeon** [comment]
> * 다크모드 버튼 바꾸기, 다크모드 테마색 변경

이거... 낮에는 본고레 테마 밤에는 바리아 테마로 바꾸고 싶다고 한 적 있지 않아?
~대화 모드 변경이었나?~ 이렇게 생각했다고 한들 모드 변경은 불편하겠다.
대화 모드를 변경할 때마다 사용자가 눈뽕을 맞을 필요는 없지...
